import type { PromptValidationResult, RefinementRequest, RefinementResult } from '@shared/types'
import { buildRefinementPrompt } from '../prompts/refinePrompt'
import type { AIProvider, PromptValidationRequest } from '../provider'
import { keychainService } from '@main/security/keychain'

const GROQ_MODEL = 'llama-3.3-70b-versatile'

interface GroqResponse {
  choices?: Array<{
    message?: {
      content?: string
    }
  }>
}

function parseValidationJson(raw: string): { verdict?: string; notes?: string } | null {
  const trimmed = raw.trim()
  try {
    return JSON.parse(trimmed) as { verdict?: string; notes?: string }
  } catch {
    // Continue with best-effort extraction.
  }

  const start = trimmed.indexOf('{')
  const end = trimmed.lastIndexOf('}')
  if (start >= 0 && end > start) {
    try {
      return JSON.parse(trimmed.slice(start, end + 1)) as { verdict?: string; notes?: string }
    } catch {
      return null
    }
  }
  return null
}

export class GroqProvider implements AIProvider {
  readonly id = 'groq'

  async isConfigured(profileId: string): Promise<boolean> {
    const apiKey = await keychainService.getGroqApiKey(profileId)
    return Boolean(apiKey)
  }

  async refinePrompt(request: RefinementRequest): Promise<RefinementResult> {
    const apiKey = await keychainService.getGroqApiKey(request.profileId)
    if (!apiKey) {
      throw new Error('Groq API key is not configured for this profile')
    }

    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: GROQ_MODEL,
        temperature: 0.2,
        messages: [
          {
            role: 'system',
            content:
              'You improve prompts by making them clearer, more specific, and more effective. Return the improved prompt text only, without any extra commentary.'
          },
          {
            role: 'user',
            content: buildRefinementPrompt(request)
          }
        ]
      })
    })

    if (!response.ok) {
      const body = await response.text()
      throw new Error(`Groq request failed: ${response.status} ${body}`)
    }

    const data = (await response.json()) as GroqResponse
    const refinedContent = data.choices?.[0]?.message?.content?.trim()

    if (!refinedContent) {
      throw new Error('Groq returned an empty refinement result')
    }

    return {
      providerId: this.id,
      model: GROQ_MODEL,
      refinedContent,
      notes: 'Generated by Groq refinement workflow.'
    }
  }

  async validatePrompt(request: PromptValidationRequest): Promise<PromptValidationResult> {
    const apiKey = await keychainService.getGroqApiKey(request.profileId)
    if (!apiKey) {
      throw new Error('Groq API key is not configured for this profile')
    }

    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: GROQ_MODEL,
        temperature: 0.1,
        messages: [
          {
            role: 'system',
            content:
              'You are a helpful prompt coach. A prompt PASSES if it has a clear task and basic structure. Return {"verdict":"pass","notes":"brief tip"} for good prompts. Return {"verdict":"needs_work","notes":"short action"} only for unclear prompts. If category/useCase/aiTarget are missing, note "Add category, use case, and AI target before sharing." Be brief.'
          },
          {
            role: 'user',
            content: [
              `Title: ${request.title}`,
              `Category: ${request.category ?? 'General'}`,
              `Use case: ${request.useCase ?? 'Not provided'}`,
              `AI target: ${request.aiTarget ?? 'Not provided'}`,
              '',
              'Prompt content:',
              request.content,
              '',
              'Is this prompt clear enough to be shared and used by others?'
            ].join('\n')
          }
        ]
      })
    })

    if (!response.ok) {
      const body = await response.text()
      throw new Error(`Groq request failed: ${response.status} ${body}`)
    }

    const data = (await response.json()) as GroqResponse
    const raw = data.choices?.[0]?.message?.content?.trim()
    if (!raw) {
      throw new Error('Groq returned an empty validation result')
    }

    const parsed = parseValidationJson(raw)

    let verdict: 'pass' | 'needs_work' = 'pass'
    let notes = 'Looks good!'

    if (parsed) {
      verdict = parsed.verdict === 'needs_work' ? 'needs_work' : 'pass'
      notes = parsed.notes?.trim() || (verdict === 'pass' ? 'Looks good!' : 'Needs some work.')
    } else {
      const lowerRaw = raw.toLowerCase()
      if (lowerRaw.includes('needs_work') || lowerRaw.includes('needs improvement') || lowerRaw.includes('not clear')) {
        verdict = 'needs_work'
        notes = 'Review and improve the prompt.'
      } else {
        notes = 'Prompt validated.'
      }
    }

    return {
      providerId: this.id,
      model: GROQ_MODEL,
      verdict,
      notes
    }
  }
}
